name = "TFS"
prefix = "tfs"
author = "TFS"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3

files = [
    "mod.cpp",
    "README.md",
    "LICENSE.md",
    "extras/addons",
    "extras/keys"
    ]

exclude = ["*.psd", "*.png", "*.tga"]


modname = "{{name}}"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

check = [
    "!version_set"
]
releasebuild = [
    "@zip TFS_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}",
    "!version_unset"
]

[header_exts]
version = "{{git \"id 8\"}}"

[scripts.version_set]
steps_windows = [
    "echo Setting version",
    "powershell -Command foreach ($f in 'mod.cpp', 'README.md', 'addons/main/CfgMods.hpp') {(Get-Content $f) -replace '[0-9]+\\.[0-9]+\\.[0-9]+', '{{semver.major}}.{{semver.minor}}.{{semver.patch}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/main/script_version.hpp') {(Get-Content $f) -replace '#define BUILD 000000', '#define BUILD {{date \"%y%m%d\"}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}"
]
only_release = true
show_output = true

[scripts.version_unset]
steps_windows = [
    "echo Unsetting version",
    "powershell -Command foreach ($f in 'mod.cpp', 'addons/main/CfgMods.hpp') {(Get-Content $f) -replace '{{semver.major}}.{{semver.minor}}.{{semver.patch}}', '0.0.0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/main/script_version.hpp') {(Get-Content $f) -replace '#define BUILD {{date \"%y%m%d\"}}', '#define BUILD 000000' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "echo -^> README.md version ready for commit (ignore until release)!"
]
only_release = true
show_output = true

