name = "TFS"
prefix = "tfs"
author = "TFS"
template = "cba"
mainprefix = "z"
folder_optionals = true


files = [
    "mod.cpp",
    "README.md",
    "LICENSE.md",
    "extras/addons",
    "extras/keys"
    ]

exclude = ["*.psd", "*.png", "*.tga"]


modname = "{{name}}"


check = [
    "!compile_scripts"
]

postbuild = [
    "!remove_compiled_scripts"
]

releasebuild = [
    "@zip @TFS_{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"


[scripts.compile_scripts]
steps_windows = [
    "echo 'Compile Arma Scripts'",
    "ArmaScriptCompiler.exe"
]

steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
show_output = false

[scripts.remove_compiled_scripts]
steps_windows = [
    "echo 'remove Compiled Scripts'",
    "powershell -Command Remove-Item './addons/*' -Recurse -Include *.sqfc"
]
steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
show_output = true