/*
    Author: Freddo

    Creates a debriefing section for admins containing all
    log messasges sent during the mission.
    Displayed in mission debriefing screen.

    Include this file in description.ext of your mission

    Example:
    class CfgDebriefingSections {
        #include "\z\tfsrhs\addons\adminmenu\debriefAdminLog.inc"
    };
*/

class tfsrhs_adminlog
{
    title = "TFSRHS Log";
    variable = "TFSRHS_adminmenu_debrief";
};
