PREP(dummy);
PREP(numToColor);
PREP(getCfgEntry);
PREP(getCfgEntryFromPath);
PREP(numToSide); // rename
PREP(numToTexture);
PREP(sideToNum);
PREP(sideToString);
PREP(sideToColor);
PREP(sideToHexColor);
PREP(sideToTexture);
PREP(sideType);
PREP(evaluateCondArray);
PREP(capitalize);
PREP(initGroupVar);
PREP(getNearestRoad);
PREP(deserializeWaypoint);
PREP(serializeWaypoint);
PREP(serializeWaypoints);
PREP(moduleUnits);
PREP(checkVersionArray);
PREP(checkTFSVersion);
PREP(arrayToStringArray);
PREP(randPosArea);
PREP(drawLines);
PREP(endMission);
PREP(edenMouseOver);
PREP(edenMouseKeyDown);
PREP(edenMouseKeyUp);
PREP(edenInit);
PREP(intro);
PREP(edenDraw);
PREP(edenHideMapObjects);
PREP(hideMapObjectsInit);
PREP(getPosVisual);
PREP(initDisplayDebriefing);
PREP(initDisplayMultiplayerSetup);
PREP(testGroupsSlottingScreen);
PREP(secondsToTime);
PREP(edenDisplayFactionIcons);
PREP(isUnconscious);
PREP(modal);
PREP(onModalOpen);
PREP(onModalClose);
PREP(createPlayerMarker);
PREP(readConfigToNamespace);
PREP(easterDate);
PREP(runAfterSettingsInit);

/////// Settings 
PREP(getKeybindString);
PREP(needRestart);
PREP(needRestartLocal);

//////Addons
PREP(getAddonAuthor);
PREP(getAddonAuthors);
PREP(getAddonName);
PREP(getAddonRequiredAddons);
PREP(getAddonRequiredVersion);
PREP(getAddonUnits);
PREP(getAddonURL);
PREP(getAddonVersion);
PREP(getAddonVersionArray);
PREP(getAddonVersionString);
PREP(getAddonWeapons);
PREP(isAddon);

///core
PREP(addItem);
PREP(attachToRel);
PREP(createLitter);
PREP(createLitterServer);
PREP(getUnitInsignia);
PREP(isAdmin);
PREP(isCurator);
PREP(isInBuilding);
PREP(screenshot);
PREP(setUnitInsignia);


////Diagnostic 
PREP(diagLog);
PREP(diagLogGlobal);
PREP(diagLogServer);
PREP(isDebug);
PREP(log);
PREP(logGlobal);
PREP(logServer);

////Sounds
PREP(decibelToGain);
PREP(gainToDecibel);
PREP(getSoundDistance);
PREP(getSoundDuration);
PREP(getSoundFile);
PREP(getSoundPitch);
PREP(getSoundVolume);
PREP(isSpeaking);
PREP(loop3dSound);
PREP(loop3dSoundLocal);
PREP(play3dSound);
PREP(play3dSoundLocal);
PREP(playSound);
PREP(playSoundLocal);
PREP(playSound3d);
PREP(say3d);
PREP(say3dLocal);
PREP(speak3d);
PREP(speak3dLocal);
PREP(stop3dSound);
PREP(stop3dSoundLocal);

////Videos
PREP(playVideo);
PREP(playVideoOnce);
PREP(videoKeyDown);