PREP(dummy);
PREP(numToColor);
PREP(getCfgEntry);
PREP(getCfgEntryFromPath);
PREP(numToSide);
PREP(numToTexture);
PREP(sideToNum);
PREP(sideToString);
PREP(sideToColor);
PREP(sideToHexColor);
PREP(sideToTexture);
PREP(sideType);
PREP(evaluateCondArray);
PREP(isAdmin);
PREP(capitalize);
PREP(initGroupVar);
PREP(getNearestRoad);
PREP(deserializeWaypoint);
PREP(serializeWaypoint);
PREP(serializeWaypoints);
PREP(moduleUnits);
PREP(checkVersionArray);
PREP(checkTFSRHSVersion);
PREP(arrayToStringArray);
PREP(randPosArea);
PREP(drawLines);
PREP(endMission);
PREP(edenMouseOver);
PREP(edenMouseKeyDown);
PREP(edenMouseKeyUp);
PREP(edenInit);
PREP(intro);
PREP(edenDraw);
PREP(edenHideMapObjects);
PREP(hideMapObjectsInit);
PREP(getPosVisual);
PREP(initDisplayDebriefing);
PREP(initDisplayMultiplayerSetup);
PREP(testGroupsSlottingScreen);
PREP(secondsToTime);
PREP(edenDisplayFactionIcons);
PREP(isUnconscious);
PREP(modal);
PREP(onModalOpen);
PREP(onModalClose);
PREP(createPlayerMarker);
PREP(readConfigToNamespace);
PREP(easterDate);
PREP(runAfterSettingsInit);

//// Addons 
PREP (getAddonAuthor);
PREP (getAddonAuthors);
PREP (getAddonName);
PREP (getAddonRequiredAddons);
PREP (getAddonRequiredVersion);
PREP (getAddonUnits);
PREP (getAddonURL);
PREP (getAddonVersion);
PREP (getAddonVersionArray);
PREP (getAddonVersionString);
PREP (getAddonWeapons);
PREP (isAddon);
////// Common 
PREP (addItem);
PREP (attachToRel);
PREP (createLitter);
PREP (createLitterServer);
PREP (getUnitInsignia);
PREP (isAdmin);
PREP (isInBuilding);

/////// Settings 
PREP (getKeybindString);
PREP (needRestart);
PREP (needRestartLocal);

///tfsrhs
// PREP(customMark);
// PREP(initDB);
// PREP(initIntelObject);
// PREP(isAdmin);
// PREP(missionInitialization);
// PREP(objectMarkers);
// PREP(paramToBool);
// PREP(rptLog);
// PREP(uavIntro);
