PREP(dummy);
PREP(numtoColor);
PREP(getCfgEntry);
PREP(getCfgEntryfromPath);
PREP(numtoside);
PREP(numtotexture);
PREP(sidetoNum);
PREP(sidetoString);
PREP(sidetoColor);
PREP(sidetoHexColor);
PREP(sidetotexture);
PREP(sidetype);
PREP(evaluateCondArray);
PREP(isadmin);
PREP(capitalize);
PREP(initgroupVar);
PREP(getNearestroad);
PREP(deserializeWaypoint);
PREP(serializeWaypoint);
PREP(serializewaypoints);
PREP(moduleunits);
PREP(checkVersionArray);
PREP(checkTFSVersion);
PREP(arraytoStringArray);
PREP(randPosArea);
PREP(drawLines);
PREP(endMission);
PREP(edenMouseOver);
PREP(edenMouseKeydown);
PREP(edenMouseKeyUp);
PREP(edeninit);
PREP(intro);
PREP(edenDraw);
PREP(edenHideMapObjects);
PREP(hideMapObjectsinit);
PREP(getPosVisual);
PREP(initDisplayDebriefing);
PREP(initDisplayMultiplayersetup);
PREP(testgroupsSlottingScreen);
PREP(secondstotime);
PREP(edenDisplayfactionIcons);
PREP(isUnconscious);
PREP(modal);
PREP(onmodalOpen);
PREP(onmodalClose);
PREP(createplayerMarker);
PREP(readConfigtonamespace);
PREP(easterdate);
PREP(runAftersettingsinit);

// Addons
PREP (getAddonAuthor);
PREP (getAddonAuthors);
PREP (getAddonname);
PREP (getAddonRequiredAddons);
PREP (getAddonrequiredVersion);
PREP (getAddonunits);
PREP (getAddonURL);
PREP (getAddonVersion);
PREP (getAddonVersionArray);
PREP (getAddonVersionstring);
PREP (getAddonweapons);
PREP (isAddon);
// Common
PREP (addItem);
PREP (attachtorel);
PREP (createLitter);
PREP (createLitterServer);
PREP (getUnitinsignia);
PREP (isadmin);
PREP (isinBuilding);

// settings
PREP (getKeybindstring);
PREP (needRestart);
PREP (needRestartlocal);

// tfs
// PREP(customMark);
// PREP(initDB);
// PREP(initintelObject);
// PREP(isadmin);
// PREP(missioninitialization);
// PREP(objectMarkers);
// PREP(paramtoBool);
// PREP(rptlog);
// PREP(uavintro);