name: CI

on: [push, pull_request]

jobs:
  test-configs:
    name: Archive test configs
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Archive test configs
        uses: actions/upload-artifact@v2
        with:
          name: test configs
          path: test/*.json
          if-no-files-found: error

  windows-build:
    name: Windows build
    runs-on: windows-2019
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Windows 64 bit
        run: mkdir build-win64 && cd build-win64 && cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 .. && cmake --build . --config Release

      - name: Upload Windows 64 bit
        uses: actions/upload-artifact@v2
        with:
          name: Windows x64
          path: Release
          if-no-files-found: error
