jobs:
  windows:
    name: Windows

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create work drive
        run: 'subst P: .'

      - uses: arma-actions/sqfc@latest
        with:
          directory: .